/// Flutter icons SnackmateIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SnackmateIcons
///      fonts:
///       - asset: fonts/SnackmateIcons.ttf
///
/// 
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
///
import 'package:flutter/widgets.dart';

class SnackmateIcons {
  SnackmateIcons._();

  static const _kFontFam = 'SnackmateIcons';

  static const IconData chat_alt = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData user_outline = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData search_outline = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData heart_filled = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData heart = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData edit = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData home_outline = const IconData(0xe806, fontFamily: _kFontFam);
}
